---
title: "01 Linear Regression"
author: "Paul Tuccinardi"
date: "`r Sys.Date() `"
output: html_document
---

Introduction and Goal:
The goal of this notebook is to introduce the concept of linear regression, a fundamental statistical method used for modeling the relationship between a dependent variable and one or more independent variables. We will explore how to implement linear regression in R, interpret the results, and evaluate the model's performance.

``` {r loaddata}
knitr::opts_chunk$set(echo = TRUE)
library(readr)
library(dplyr)
library(ggplot2)

data <- read_csv("housing.csv")

data <- data %>%
    select(median_income, median_house_value)

head(data)

corrr <- cor(data$median_income, data$median_house_value)

cat(paste("Pearson Correlation Coefficient:", round(corrr, 4), "\n"))

ggplot(data, aes(x = median_income, y = median_house_value)) +
    geom_point(alpha = 0.5) +
    labs(title = "Scatter Plot of Median Income vs. Median House Value",
         x = "Median Income",
         y = "Median House Value") +
    theme_minimal()
```
``` {r .linear_regression}
simple_model <- lm(median_house_value ~ median_income, data = data)
summary(simple_model)

ggplot(data, aes(x = median_income, y = median_house_value)) +
    geom_point(alpha = 0.5) +
    geom_smooth(method = "lm", color = "blue") +
    labs(title = "Linear Regression: Median Income vs. Median House Value",
         x = "Median Income",
         y = "Median House Value") +
    theme_minimal()
```